steps:

  - id: 'deploy backend'
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--version=prod']

  - id: 'deploy dispatch.yaml'
    name: "gcr.io/cloud-builders/gcloud"
    args: [ 'app', 'deploy', '/workspace/dispatch.yaml' ]
