steps:

  - id: 'mvn package'
    name: 'gcr.io/cloud-builders/mvn'
    args: ['-e', '-DskipTests', 'package', 'appengine:deploy']

  - id: 'deploy dispatch.yaml'
    name: "gcr.io/cloud-builders/gcloud"
    args: [ 'app', 'deploy', '/workspace/dispatch.yaml' ]
